version: '3'
services:
  mariadb:
    image: sv00360113/mariadb
    container_name: mysql
    hostname: dbapp
    restart: always
    privileged: true
    ports:
       - "3306:3306"
       - "2222:22"
  wso2ei:
    image: sv00360113/wso2ei
    container_name: wso2ei
    hostname: webapp
    restart: always
    privileged: true
    ports:
       - "9444:9445"
       - "2200:22"
    links:
       - mariadb
    depends_on:
       - mariadb
